name: Continuous Integration

on: # 이벤트
  pull_request:
    branches: [ main ]

jobs:
  build-and-test: # 잡 이름

    runs-on: ubuntu-latest # 실행 환경

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # jdk 배포판 설정 - AdoptOpenJDK

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootApiJar

      - name: Run tests
        run: ./gradlew test
