name: Deploy Docker Container

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: devridge docker
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and Restart Docker Container
        run: |
          ssh -o StrictHostKeyChecking=no gitaction@3.38.125.102 << EOF
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/devridge:latest
            docker stop devridge-container || true
            docker rm devridge-container || true
            docker run -d --name devridge-container -p 8081:8081 --env SPRING_PROFILES_ACTIVE=prod -v ~/setting:/config ${{ secrets.DOCKER_HUB_USERNAME }}/devridge:latest
          EOF
